#pragma config(Sensor, dgtl1,  Bumper,         sensorTouch)
#pragma config(Sensor, dgtl2,  PnuematicArm,   sensorDigitalOut)
#pragma config(Sensor, dgtl12, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port1,           intake,        tmotorVex269_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#define vexMotorMAX 127
#define vexMotorMIN 0

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	while(true)
	{
		SensorValue(greenLED) = 1;

		if(SensorValue(Bumper) == 0)
		{
			motor[right] = 127;
			motor[left] = 127;
		}
		if(SensorValue(Bumper) == 1)
		{
			SensorValue(greenLED) = 0;
			motor[right] = 0;
			motor[left] = 0;
			motor[intake] = 127;
			wait1Msec(6000);
			motor[intake] = 0;
			SensorValue[dgtl1] = 1;
			wait1Msec(1000);
			SensorValue[dgtl1] = 0;
			wait1Msec(1000);
			SensorValue[dgtl1] = 1;
		}
}
}


task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// drive control
		motor[left] = vexRT[Ch3];
		motor[right] = vexRT[Ch2];

		// intake
		if(vexRT[Btn5U] == 1)
		{
			motor[intake] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[intake] = -127;
		}
		else
		{
			motor[intake] = 0;
		}

		UserControlCodePlaceholderForTesting();
	}
}
